server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: "@123Kartik"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
